[package]
name = "macaddress"
version = "0.1.0"
authors = ["Andrew Baumhauer <andy@baumhauer.us>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/abaumhauer/macaddress"
homepage = "https://github.com/abaumhauerrust-lang/macaddress"
documentation = "https://doc.rust-lang.org/macaddress"
description = """
A library to generate and parse IEEE MAC-48 media access control addresses.
"""

[dependencies]
rustc-serialize = "*"
serde = { version = "*", optional = true }
